import Image from 'next/image'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
       <ol>
        <li>.next: This folder is generated by Next.js and contains the compiled output of your application, including optimized HTML, CSS, and JavaScript files.</li>
        <li>node_modules: This is where all the project dependencies are installed. You don't need to worry about this folder, as npm manages it for you.</li>
        <li>public: This is the folder where you can place static assets like images, fonts, and other files that need to be publicly accessible.</li>
        <li>src: You can create this folder to organize your application's source code, although Next.js doesn't enforce any specific folder structure. </li>
        <li>pages: This is where you'll create your app's pages. Each JavaScript or TypeScript file in this folder will become a route in your application.</li>
        <li>styles: This folder is for your global styles. You can have CSS or Sass files here that will be applied throughout your app.</li>
        <li>components: This is where you can put your reusable React components. Organize your components into subfolders based on their functionality.</li>
        <li>utils: This folder is for utility functions, helper classes, or other code snippets that are used across different parts of your application.</li>
        <li>package.json: This file contains metadata about your project, including its dependencies and scripts.</li>
        <li>package-lock.json: This file is automatically generated by npm to lock down the specific versions of your dependencies.</li>
        <li>tsconfig.json (if you're using TypeScript): This file contains TypeScript configuration options.</li>
        <li>README.md: This is where you can document your project and provide information for other developers.</li>
       
       </ol>
    </main>
  )
}
